version: "26.1"
services: 
  app:
    build: .
    volumes: 
      - .:/django
    ports:
      - 8000:8000
    image: myapp:django
    container_name: app_container
    command: gunicorn Proyecto.wsgi:application --bind 0.0.0.0:8000